name: Publish to NPM with Provenance

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    # Add permissions for OIDC token required for provenance
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Publish to NPM with provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: npm publish --provenance

      - name: Verify provenance
        run: |
          echo "Package published with provenance. Users can verify with:"
          echo "npm audit signatures"
